blank_issues_enabled: false
contact_links:
  - name: Internal release task tracking (temporary)
    url: https://github.com/t-tonton/note/issues
    about: During internal phase, release tasks are tracked separately.
